# Generated by Django 5.1.4 on 2025-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_is_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='photos/profile.jpg', upload_to='photos/profile-pics/'),
        ),
    ]
