# Generated by Django 5.1.4 on 2025-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images\\profile-pics\\profile.jpg', upload_to='images/profile-pics/'),
        ),
    ]
