# Generated by Django 5.1.4 on 2025-01-17 08:11

from django.db import migrations, models

def create_uncategorized(apps, schema_editor):
    Category = apps.get_model('theblog', 'Category')
    Category.objects.get_or_create(
        name='Uncategorized',
        defaults={'slug': 'uncategorized'}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_alter_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RunPython(create_uncategorized)
    ]
