# Generated by Django 5.1.4 on 2025-01-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_post_category_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
