# Generated by Django 5.1.4 on 2025-01-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
