# Generated by Django 5.1.4 on 2025-01-23 08:19

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=CKEditor5Field(),
        ),
    ]
