# Generated by Django 5.1.4 on 2025-01-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the title to read more...', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='Click the title to read more...', upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
