# Generated by Django 5.1.4 on 2025-01-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='photos/no-image.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
