# Generated by Django 5.1.4 on 2025-02-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/BLog.jpeg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
